name: smart_clock_widget
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  analog_clock: ^0.1.1
  provider: ^6.0.3
  fluent_ui: #^4.6.1
    git: https://github.com/YehudaKremer/fluent_ui.git
  fluentui_system_icons: ^1.1.181
  system_theme: ^2.0.0
  window_manager: ^0.3.4
  shared_preferences: ^2.0.13
  intl: ^0.18.0
  hotkey_manager: ^0.1.7
  im_animations: ^0.1.2
  schedulers: ^1.0.1
  win_toast: ^0.3.0
  flutter_colorpicker: ^1.0.3
  hexcolor: ^3.0.1
  wave: ^0.2.2
  file_picker: ^5.0.1
  cached_network_image: ^3.2.2
  win32: ^4.1.4
  ffi: ^2.0.1
  dio: ^5.1.2
  url_launcher: ^6.1.5
  path_provider: ^2.0.11
  sentry_flutter: ^7.6.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
